### ISSUE TITLE
ValueError: input operand has more dimensions than allowed by the axis remapping

### ISSUE THREAD

**Issue by helen9975** [robobase-org/robobase#6]
Hi, I've come across an error when running with the command `python train.py` and the following arguments:
`'method=act', 'launch=act_pixel_bigym', 'env=bigym/reach_target_dual', 'wandb.name=act_bigym_reach_target', 'env.episode_length=100', 'demos=-1', 'batch_size=256', 'replay.nstep=1', 'pixels=true'`

> Exception has occurred: ValueError
Caught ValueError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/helen/miniconda3/envs/bigym/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/helen/miniconda3/envs/bigym/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 33, in fetch
    data.append(next(self.dataset_iter))
  File "/home/helen/Documents/bimanual/robobase/robobase/replay_buffer/uniform_replay_buffer.py", line 844, in __iter__
    yield self.sample_single()
  File "/home/helen/Documents/bimanual/robobase/robobase/replay_buffer/uniform_replay_buffer.py", line 822, in sample_single
    return self._sample_non_sequential(global_index)
  File "/home/helen/Documents/bimanual/robobase/robobase/replay_buffer/uniform_replay_buffer.py", line 760, in _sample_non_sequential
    replay_sample[name + "_tp1"] = episode[name][next_obs_idxs]
ValueError: input operand has more dimensions than allowed by the axis remapping
  File "/home/helen/Documents/bimanual/robobase/robobase/method/act.py", line 383, in update
    batch = next(replay_iter)
  File "/home/helen/Documents/bimanual/robobase/robobase/workspace.py", line 520, in _perform_updates
    self.agent.update(
  File "/home/helen/Documents/bimanual/robobase/robobase/workspace.py", line 605, in _pretrain_on_demos
    pretrain_metrics = self._perform_updates()
  File "/home/helen/Documents/bimanual/robobase/robobase/workspace.py", line 321, in _train
    self._pretrain_on_demos()
  File "/home/helen/Documents/bimanual/robobase/robobase/workspace.py", line 314, in train
    raise e
  File "/home/helen/Documents/bimanual/robobase/robobase/workspace.py", line 314, in train
    raise e
  File "/home/helen/Documents/bimanual/robobase/train.py", line 20, in main
    workspace.train()
  File "/home/helen/Documents/bimanual/robobase/train.py", line 24, in <module>
    main()
ValueError: Caught ValueError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/helen/miniconda3/envs/bigym/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/helen/miniconda3/envs/bigym/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 33, in fetch
    data.append(next(self.dataset_iter))
  File "/home/helen/Documents/bimanual/robobase/robobase/replay_buffer/uniform_replay_buffer.py", line 844, in __iter__
    yield self.sample_single()
  File "/home/helen/Documents/bimanual/robobase/robobase/replay_buffer/uniform_replay_buffer.py", line 822, in sample_single
    return self._sample_non_sequential(global_index)
  File "/home/helen/Documents/bimanual/robobase/robobase/replay_buffer/uniform_replay_buffer.py", line 760, in _sample_non_sequential
    replay_sample[name + "_tp1"] = episode[name][next_obs_idxs]
ValueError: input operand has more dimensions than allowed by the axis remapping

This is with the default demonstrations.

Any idea what's going on?

**Comment by younggyoseo** [comment]
Hi Helen, 

I was not able to reproduce the bug with the below command:

```
CUDA_VISIBLE_DEVICES=0 DISPLAY=:0.0 python3 train.py method=act launch=act_pixel_bigym env=bigym/reach_target_dual wandb.name=act_bigym_reach_target_dual batch_size=256 demos=-1 replay.nstep=1 pixels=true env.episode_length=100
```

Could you please try running experiments on different machines or different setups? I want to help but couldn't do it if I can't reproduce the issue. Thank you!

**Comment by helen9975** [comment]
This was an issue only specific to machine, works fine on other machines. Thanks!
